version: "3.8"

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # Ensures FastAPI starts only after PostgreSQL is ready
    env_file:
      - .env  

  db:
    image: postgres:15
    restart: unless-stopped  
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      retries: 5
      start_period: 5s

volumes:
  postgres_data:  
